# Generated by Django 2.2.16 on 2022-02-25 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20220210_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to=settings.AUTH_USER_MODEL, verbose_name='в избранном у'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='in_shopping_cart_of',
            field=models.ManyToManyField(blank=True, related_name='in_shopping_cart_of', to=settings.AUTH_USER_MODEL, verbose_name='в списке покупок у'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=70, verbose_name='название'),
        ),
    ]
