# Generated by Django 2.2.16 on 2022-02-26 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220216_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptions_of_the_user',
            field=models.ManyToManyField(blank=True, related_name='subscriptions_to_the_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
